# Seminars 3&4

## GitHub

Your final project should ba availible on GitHub

Instructions:

*   [How to register](https://docs.github.com/en/get-started/start-your-journey/creating-an-account-on-github)
*   [How to create a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/quickstart-for-repositories)
*   [How to add collaborators](https://docs.github.com/ru/account-and-profile/how-tos/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

## Pandas

On the previous seminar we worked with population of different countries, we had 2 arrays: data and the names of the countries. It is not convenient, better have one *table*, like in Excel.

Let's try it in Numpy:

In [ ]:
import numpy as np

dummy_data = np.array([['A', 12, 13],
                      ['B', 4, 5],
                      ['C', 8, 10]])
dummy_data

array([['A', '12', '13'],
       ['B', '4', '5'],
       ['C', '8', '10']], dtype='<U21')

All of the elements are strings! Because in Numpy array all elements must have same type.

We cannot compute anything:

In [ ]:
dummy_data[0][1], dummy_data[0][2]

(np.str_('12'), np.str_('13'))

In [ ]:
#error! - cannot multiply strings
dummy_data[0][1] * dummy_data[0][2]

TypeError: can't multiply sequence by non-int of type 'numpy.str_'

Pandas - library for working with tables (datasets)

Why use pandas:



*   Convenient table representation
*   A lot of functions for tables (as in Excel)
*   Visualization (embedded + some libraries are design for pandas dataFrames)




Documentation - https://pandas.pydata.org/docs/

In [ ]:
import pandas as pd

Table in pandas is called `DataFrame`

In [ ]:
df = pd.DataFrame([['A', 12, 13],
                      ['B', 4, 5],
                      ['C', 8, 10]])
df

   0   1   2
0  A  12  13
1  B   4   5
2  C   8  10

In [ ]:
type(df)

pandas.core.frame.DataFrame

The columns are `Series` - 1D array, with index labels.

In [ ]:
df[0]

0    A
1    B
2    C
Name: 0, dtype: object

In [ ]:
type(df[0])

pandas.core.series.Series

We can take the values of the table as a numpy array

In [ ]:
df.values

array([['A', 12, 13],
       ['B', 4, 5],
       ['C', 8, 10]], dtype=object)

Some real data  - Titanic datasets

In [ ]:
!wget https://raw.githubusercontent.com/Majid-Sohrabi/MLDM-2025/refs/heads/main/01-intro/train.csv
df = pd.read_csv("train.csv")
df.head()

--2025-10-10 15:41:37--  https://raw.githubusercontent.com/Majid-Sohrabi/MLDM-2025/refs/heads/main/01-intro/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60302 (59K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>]  58.89K  --.-KB/s    in 0.02s

2025-10-10 15:41:37 (3.45 MB/s) - ‘train.csv’ saved [60302/60302]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Columns:

*  **PassengerId** - The ID of the passenger
*   **Survived** - 	Survival of the passenger;	0 = No, 1 = Yes
* **Pclass**	- Ticket class;	1 = 1st, 2 = 2nd, 3 = 3rd
* **Sex**	- Sex of the passenger
*   **Age** -	Age in years
*   **SibSp**	- Number of siblings / spouses aboard the Titanic
* **Parch**	- Number of parents / children aboard the Titanic
* **Ticket**	- Ticket number
* **Fare**	- Passenger fare
* **Cabin**	- Cabin number
* **Embarked**	- Port of Embarkation;	C = Cherbourg, Q = Queenstown, S = Southampton

First rows:

In [ ]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

Last rows:

In [ ]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

Random rows:

In [ ]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
274,275,1,3,"Healy, Miss. Hanora ""Nora""",female,NaN,0,0,370375,7.7500,NaN,Q
577,578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.0,1,0,13507,55.9000,E44,S

We can start by checking the basic information about the DataFrame

### Variables' types

There are numerical and categorical (nominal, ordinal) variables.

We need to know the type of every variable to work with it.

Let's check the types of columns in `df` and the description of the columns and try to understand the type of every feature of passengers.

In [ ]:
#Types of columns
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.shape

(891, 12)

In [ ]:
#number of rows
len(df)

891

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Indexing

We can choose columns

In [ ]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

The columns are `Series` - 1D array, with index labels.

In [ ]:
type(df['Age'])

pandas.core.series.Series

Why index labels matter? Why are they bold in DataFrame and why are they preserved in Series?

...

Because they are ids of rows/elements and they are not always numbers 0, 1, ...


Let's firstly look on how to choose rows: methods `loc` and `iloc`

In [ ]:
#choose row with index = 1
df.loc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [ ]:
#choose row, which relative position is 1
df.iloc[1]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

No difference? Let's check the following example:

In [ ]:
np.random.seed(0)
sample = df.sample(3)

sample

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
495,496,0,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C
648,649,0,3,"Willey, Mr. Edward",male,NaN,0,0,S.O./P.P. 751,7.5500,NaN,S
278,279,0,3,"Rice, Master. Eric",male,7.0,4,1,382652,29.1250,NaN,Q

The relative position 1 is occupied by Edward (648 index)

In [ ]:
sample.iloc[1]

PassengerId                   649
Survived                        0
Pclass                          3
Name           Willey, Mr. Edward
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket              S.O./P.P. 751
Fare                         7.55
Cabin                         NaN
Embarked                        S
Name: 648, dtype: object

But there is no index 1, so `loc` will give an error:

In [ ]:
#errors
sample.loc[1]

KeyError: 1

In [ ]:
sample.loc[648]

PassengerId                   649
Survived                        0
Pclass                          3
Name           Willey, Mr. Edward
Sex                          male
Age                           NaN
SibSp                           0
Parch                           0
Ticket              S.O./P.P. 751
Fare                         7.55
Cabin                         NaN
Embarked                        S
Name: 648, dtype: object

When we take the column of our sample, the indices will be perserved.

In [ ]:
sample['Age']

495    NaN
648    NaN
278    7.0
Name: Age, dtype: float64

### Add/delete columns

We often need to create new features based on old ones or delete the extr ones.

In [ ]:
df['Random'] = np.random.rand(len(df))
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,0.404774
339,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5000,T,S,0.922299

There was no `'Random'` column, we created it (like in python `dict`, just entered a new key)

We also can use old columns to create new

In [ ]:
df['Fare'] * 2

0       14.5000
1      142.5666
2       15.8500
3      106.2000
4       16.1000
         ...
886     26.0000
887     60.0000
888     46.9000
889     60.0000
890     15.5000
Name: Fare, Length: 891, dtype: float64

In [ ]:
df['Double_Fare'] =  df['Fare'] * 2
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.275,NaN,S,0.457059,62.55
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.000,NaN,S,0.208253,0.00

In [ ]:
df['Fare_Random'] =  df['Fare'] + df['Random']
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random
125,126,1,3,"Nicola-Yarred, Master. Elias",male,12.0,1,0,2651,11.2417,NaN,C,0.675689,22.4834,11.917389
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.0,1,1,C.A. 37671,15.9000,NaN,S,0.506863,31.8000,16.406863

In [ ]:
df['Big_Fare'] =  (df['Fare'] > 100).astype('int64')
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S,0.556133,40.5,20.806133,0
580,581,1,2,"Christy, Miss. Julie Rachel",female,25.0,1,1,237789,30.00,NaN,S,0.244570,60.0,30.244570,0


**Task** Create column `FamilySize` that will contain the size of the passenger's family. F.e. if passenger has 4 siblings and 2 parent on the Titanic, their family size is 7.

In [ ]:
#your code here
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.sample(13)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize
573,574,1,3,"Kelly, Miss. Mary",female,NaN,0,0,14312,7.7500,NaN,Q,0.773259,15.5000,8.523259,0,1
750,751,1,2,"Wells, Miss. Joan",female,4.0,1,1,29103,23.0000,NaN,S,0.620126,46.0000,23.620126,0,3
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C,0.411616,110.8834,55.853316,0,2
245,246,0,1,"Minahan, Dr. William Edward",male,44.0,2,0,19928,90.0000,C78,Q,0.441321,180.0000,90.441321,0,3
352,353,0,3,"Elias, Mr. Tannous",male,15.0,1,1,2695,7.2292,NaN,C,0.938412,14.4584,8.167612,0,3
220,221,1,3,"Sunderland, Mr. Victor Francis",male,16.0,0,0,SOTON/OQ 392089,8.0500,NaN,S,0.963197,16.1000,9.013197,0,1
410,411,0,3,"Sdycoff, Mr. Todor",male,NaN,0,0,349222,7.8958,NaN,S,0.232773,15.7916,8.128573,0,1
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S,0.291389,17.3250,8.953889,0,1
191,192,0,2,"Carbines, Mr. William",male,19.0,0,0,28424,13.0000,NaN,S,0.914863,26.0000,13.914863,0,1
199,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0000,NaN,S,0.473143,26.0000,13.473143,0,1
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,0.781193,455.0500,228.306193,1,2
595,596,0,3,"Van Impe, Mr. Jean Baptiste",male,36.0,1,1,345773,24.1500,NaN,S,0.278117,48.3000,24.428117,0,3
109,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q,0.267207,48.3000,24.417207,0,2

**Task** Create  column `isAlone` that contains `True/False` - information that passenger is travelling alone.

In [ ]:
#your code here
df['isAlone'] = df['FamilySize'] == 1
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize,isAlone
462,463,0,1,"Gee, Mr. Arthur H",male,47.0,0,0,111320,38.5000,E63,S,0.066074,77.0000,38.566074,0,1,True
681,682,1,1,"Hassab, Mr. Hammad",male,27.0,0,0,PC 17572,76.7292,D49,C,0.960813,153.4584,77.690013,0,1,True
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C,0.156383,30.4916,15.402183,0,3,False

All the new columns were created using math or bool operations. What if we have some more complex function?

For example, we want to have column 'name_length'

In [ ]:
len(df['Name'])

891

The code does not compute `len` for every name, but to the Series itself.

To apply function we can use `apply` (or `for`-loop, but they are slow)

In [ ]:
df['Name'].apply(len)

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

**Task:** Every full name contains a title (Mr, Mrs, ...), extract it and put into new column.

In [ ]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize,isAlone
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.125,NaN,Q,0.857125,58.25,29.982125,0,6,False

In [ ]:
s = 'Rice, Master. Eugene'
s.split(', ')[1].split('.')[0]

'Master'

In [ ]:
def extract_title(s):
  #Hassab, Mr. Hammad
  #Jardin, Mr. Jose Neto
  #your code here
  return s.split(', ')[1].split('.')[0]



df['Title'] = df['Name'].apply(extract_title)

df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize,isAlone,Title
540,541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0000,B22,S,0.367475,142.0000,71.367475,0,3,False,Miss
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.0,0,0,PC 17582,153.4625,C125,S,0.598316,306.9250,154.060816,1,1,True,Miss
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S,0.657862,139.1000,70.207862,0,11,False,Mr
219,220,0,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.5000,NaN,S,0.600213,21.0000,11.100213,0,1,True,Mr
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,NaN,S,0.107211,16.8084,8.511411,0,2,False,Mr

In [ ]:
df.sample(5)[['Name', 'Title']]

                                               Name Title
705  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    Mr
593                              Bourke, Miss. Mary  Miss
96                        Goldschmidt, Mr. George B    Mr
701                Silverthorne, Mr. Spencer Victor    Mr
836                                Pasic, Mr. Jakob    Mr

To delete column/rows we can use `drop` function

In [ ]:
df.drop(columns=['Big_Fare', 'Fare_Random', 'Double_Fare', 'Random'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,False,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,True,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,True,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,False,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,True,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,True,Mr

In [ ]:
df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize,isAlone,Title
785,786,0,3,"Harmer, Mr. Abraham (David Lishin)",male,25.0,0,0,374887,7.2500,NaN,S,0.396610,14.5000,7.646610,0,1,True,Mr
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S,0.947822,14.5000,8.197822,0,1,True,Mr
485,486,0,3,"Lefebre, Miss. Jeannie",female,NaN,3,1,4133,25.4667,NaN,S,0.002065,50.9334,25.468765,0,5,False,Miss

But the columns are still there ...

Important: many functions which change the dataframe are not inplace, they return a **copy**

In [ ]:
new_df = df.drop(columns=['Big_Fare', 'Fare_Random', 'Double_Fare', 'Random'])
#change something in new_df
new_df['Age'] = 0
new_df['Parch'] = -12321
new_df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,-12321,A/5 21171,7.2500,NaN,S,2,False,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,-12321,PC 17599,71.2833,C85,C,2,False,Mrs

In [ ]:
#initial is untouched
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Random,Double_Fare,Fare_Random,Big_Fare,FamilySize,isAlone,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.147809,14.5000,7.397809,0,2,False,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.684934,142.5666,71.968234,0,2,False,Mrs

We need to save the changes (use `inplace=True` or `df = df.drop(...)`)

In [ ]:
#df = df.drop(columns=['Big_Fare', 'Fare_Random', 'Double_Fare', 'Random'])
df.drop(columns=['Big_Fare', 'Fare_Random', 'Double_Fare', 'Random'], inplace=True)
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
321,322,0,3,"Danoff, Mr. Yoto",male,27.0,0,0,349219,7.8958,NaN,S,1,True,Mr
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S,1,True,Mr

###Filtering

As in numpy we can filter based on some condidions (for columns)

Choosing all women on Titanic

In [ ]:
df['Sex'] == 'female'

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [ ]:
df[df['Sex'] == 'female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False,Mrs
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3,False,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,False,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,2,False,Mrs
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,1,True,Miss
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,6,False,Mrs
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,False,Miss

Choosing adults:

In [ ]:
df[df['Age'] >= 18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,False,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,True,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,6,False,Mrs
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1,True,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,True,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1,True,Mr

Ages of adults:

In [ ]:
df[df['Age'] > 18]['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
885    39.0
886    27.0
887    19.0
889    26.0
890    32.0
Name: Age, Length: 575, dtype: float64

If we have several conditions we can use & (and), | (or)

People who are younger than 18 (kids) or older than 60 (old people)

In [ ]:
df[(df["Age"]<18) |  (df["Age"]>60)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,5,False,Master
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,False,Mrs
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,3,False,Miss
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,1,True,Miss
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,6,False,Master
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,1,True,Mr
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C,3,False,Miss
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,2,False,Miss
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,3,False,Master
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,1,True,Miss

Women who are adults:

In [ ]:
df[(df['Sex'] == 'female') & (df['Age'] >= 18)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,True,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False,Mrs
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,3,False,Mrs
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1,True,Miss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,2,False,Mrs
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,2,False,Mrs
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,1,True,Miss
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,6,False,Mrs
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss

We can combine & and | and use `()`

Women who were in 1 or 2 class:

In [ ]:
df[((df['Pclass'] == 1) | (df['Pclass'] == 2)) & (df['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,False,Mrs
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,False,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,2,False,Mrs
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1,True,Miss
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1,True,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,3,False,Mrs
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,2,False,Mrs
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,2,False,Mrs
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,2,False,Mrs
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss

Something more complex - women from 18 to 25 who embarked in Cherbourg(С), or Southampton (S)

In [ ]:
df[((df['Embarked'] =='C') | (df['Embarked'] =='S')) & (df['Sex'] == 'female') &
     (df['Age'] >= 18) & (df['Age'] <= 25)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S,3,False,Miss
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S,2,False,Mrs
56,57,1,2,"Rugg, Miss. Emily",female,21.0,0,0,C.A. 31026,10.5000,NaN,S,1,True,Miss
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,6,False,Miss
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.0,0,0,343120,7.6500,NaN,S,1,True,Miss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,NaN,S,2,False,Mrs
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C,4,False,Mrs
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,2,False,Mrs
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S,1,True,Miss
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,True,Miss

After we filter our data we may want to count the number of rows (not depict them), we may use `.shape[0]`

F.e. number of adult women on the Titanic

In [ ]:
df[(df['Sex'] == 'female') & (df['Age'] >= 18)].shape[0]

206

**Task:** Compute number of people who paid more than 100 for the ticket

In [ ]:
#your code here
len(df[df['Fare'] > 100])

53

**Task:** Depict women, who travelled with more than 4 siblings

In [ ]:
#your code here
df[(df['SibSp'] > 4) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.90,NaN,S,8,False,Miss
180,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.55,NaN,S,11,False,Miss
792,793,0,3,"Sage, Miss. Stella Anna",female,NaN,8,2,CA. 2343,69.55,NaN,S,11,False,Miss
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.55,NaN,S,11,False,Miss

**Task:** Depict Names and Ages of  passengers who survived the Titanic and were in cabin G6

In [ ]:
#your code here
df[(df['Cabin'] == 'G6') & (df['Survived'] == 1)][['Name', 'Age']]

                                                  Name   Age
10                     Sandstrom, Miss. Marguerite Rut   4.0
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...  24.0

### Sorting

Sort rows by ascending age:

In [ ]:
df.sort_values('Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,2,False,Master
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,3,False,Master
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,4,False,Miss
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C,4,False,Miss
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,3,False,Master
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,1,True,Mr
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,11,False,Miss
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,1,True,Mr
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,1,True,Mr
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,False,Miss

If we want to sort in descending order:

In [ ]:
df.sort_values('Age', ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1,True,Mr
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,1,True,Mr
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,1,True,Mr
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,1,True,Mr
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,1,True,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,1,True,Mr
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,11,False,Miss
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,1,True,Mr
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,1,True,Mr
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,4,False,Miss

If we want to sort based on several columns (firstly by age, if passengers have the same age - by fare)

In [ ]:
df.sort_values(['Age', 'Fare'], ascending=[False, True])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,isAlone,Title
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1,True,Mr
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,1,True,Mr
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,1,True,Mr
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,1,True,Mr
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,1,True,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C,1,True,Miss
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S,2,False,Mrs
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,2,False,Mrs
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,1,True,Mr
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C,1,True,Mr

### Unique values, aggregating

Very often we need to check which uniqe values do we have in our data (which cities are respondents from? What steps of educations?)

In the data description it was said that there are 3 classes on Titanic, let's check it:

In [ ]:
df.Pclass.unique()

array([3, 1, 2])

Number of unique values:

In [ ]:
df.Pclass.nunique()

3

If we want to know how many passengers were in each class:

In [ ]:
df.value_counts('Pclass')

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
df.value_counts('Sex') #Counting number of men/women

Sex
male      577
female    314
Name: count, dtype: int64

**Task** What conclusions can we make bassed on the data above?

We also may want to check number of women/men in each class. We cannot do it using `value_counts` because it works with one column.

Let's use function `groupby` - it divides the data based on several columns:

In [ ]:
class_sex_groups = df.groupby(['Pclass', 'Sex'])
class_sex_groups #Some special object

After we grouped our data, we can aggregate - compute sum, mean, number of observations of the group.

If we want to compute number of people in each group:

In [ ]:
class_sex_groups['PassengerId'].count()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: PassengerId, dtype: int64

**Task** What conclusions can we make bassed on the data above?

We may want to compute the minimum fare for each group:

In [ ]:
class_sex_groups['Fare'].min()

Pclass  Sex
1       female    25.9292
        male       0.0000
2       female    10.5000
        male       0.0000
3       female     6.7500
        male       0.0000
Name: Fare, dtype: float64

# New data, new tasks

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/cstorm125/information_value/master/data/120-years-of-olympic-history-athletes-and-results/athlete_events.csv')
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [ ]:
data['Medal'].unique()

array([nan, 'Gold', 'Bronze', 'Silver'], dtype=object)

In [ ]:
data.shape

(271116, 15)

**Task** Investigate features, name their types:

Columns :
* **ID** - Unique number for each athlete
* **Name** - Athlete's name
* **Sex** - M or F
* **Age** - Integer
* **Height** - In centimeters
* **Weight** - In kilograms
* **Team** - Team name
* **NOC** - National Olympic Committee 3-letter code
* **Games** - Year and season
* **Year** - Integer
* **Season** - Summer or Winter
* **City** - Host city
* **Sport**  - Sport
* **Event** - Event
* **Medal** - Gold, Silver, Bronze, or NA


**Task** How many athletes are heavier than 80 kgs?

In [ ]:
#your code here
data[data['Weight'] > 80].shape[0]

44854


**Task** How many female athletes are shorter than 1.85 m?

In [ ]:
#your code here
data[(data['Height'] < 185) & (data['Sex'] == 'F')].shape[0]

65357


**Task** In how many Olympic games did Edgar Lindenau Aabye participated in?

In [ ]:
#your code here
data[data['Name'] == 'Edgar Lindenau Aabye']['Games'].nunique()

1


**Task** How many gold medals did China win in diving during summer Olympic Games?

In [ ]:
#your code here
data[(data['Medal'] == 'Gold') & (data['Team'] == 'China') & (data['Sport'] == 'Diving') & (data['Season'] == 'Summer')].shape[0]

56

**Task** In which cities were box competitions held before year 2000 (including 2000)?

In [ ]:
#your code here
data[(data['Year'] <= 2000) & (data['Sport'] == 'Boxing')]['City'].unique()

array(['London', 'Seoul', 'Munich', 'Mexico City', 'Paris', 'Roma',
       'Helsinki', 'Sydney', 'Montreal', 'Atlanta', 'Moskva',
       'Los Angeles', 'Barcelona', 'Tokyo', 'Antwerpen', 'Melbourne',
       'Berlin', 'Amsterdam', 'St. Louis'], dtype=object)

**Task** How many (total) gold and silver medals did Kazakhstan won in competition `Weightlifting Women's Middleweight`?

In [ ]:
#your code here
data[(data['Team'] == 'Kazakhstan') & (data['Event'] == "Weightlifting Women's Middleweight")&
     ((data['Medal'] == 'Gold') | (data['Medal'] == 'Silver'))].shape[0]

2

**Task** Compute the total number of times an athelete participated in Olympic games, depict the top-5 people who participated in most games.

In [ ]:
#your code here
data.groupby('Name')['Games'].nunique().sort_values(ascending=False)[:5]

Name
Ian Millar                         10
Hubert Raudaschl                    9
Afanasijs Kuzmins                   9
Raimondo D'Inzeo                    8
Nino Salukvadze (-Machavariani)     8
Name: Games, dtype: int64

**Task** Create column with BMI of an athlete

$BMI = \frac{m}{h^2}$

where $m$ - weight in kg, $h$ - height in meters.

In [ ]:
#your code here
data['BMI'] = data['Weight'] / ((data['Height'] / 100) ** 2)

data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,BMI
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,24.691358
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,20.761246
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,NaN
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,23.959094

**Task** Standerd cetegories for BMI:

*   $< 18.5$ - Underweight
*   $[18.5; 25.0)$  - Normal
*   $[25.0; 30.0)$ - Overweight
*   $>= 30.0$ - Obese


Compute the BMI category for every athelete, save to `Category_BMI` column (if BMI was NaN - category should also be NaN). Compute number of athletes in every category.

In [ ]:
#your code here
def bmi_categ(bmi):
  if bmi < 18.5:
    return 'Underweight'
  if 18.5 <= bmi < 25:
    return 'Normal'
  if 25 <= bmi < 30:
    return 'Overweight'
  if bmi >= 30:
    return  'Obese'

  return np.nan

data['Category_BMI'] = data['BMI'].apply(bmi_categ)
data.sample(4)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,BMI,Category_BMI
237414,119071,Kristina Minna Telde,F,37.0,166.0,54.0,Sweden,SWE,2012 Summer,2012,Summer,London,Equestrianism,"Equestrianism Mixed Dressage, Individual",NaN,19.596458,Normal
135017,67937,Lee Hui-Cheng,F,16.0,166.0,68.0,Chinese Taipei,TPE,1984 Summer,1984,Summer,Los Angeles,Athletics,Athletics Women's Javelin Throw,NaN,24.677021,Normal
248276,124300,"Marinus ""Rinus"" van den Berge",M,24.0,171.0,65.0,Netherlands,NED,1924 Summer,1924,Summer,Paris,Athletics,Athletics Men's 100 metres,NaN,22.229062,Normal
149894,75172,Margit Mark-Nemeshzi,F,24.0,163.0,54.0,Hungary,HUN,1968 Summer,1968,Summer,Mexico City,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,20.324438,Normal

In [ ]:
data['Category_BMI'].value_counts()

Category_BMI
Normal         164473
Overweight      29877
Underweight      8099
Obese            4404
Name: count, dtype: int64

**Task** The results may be surprising - there seems to be a lot of "obese" atheletes... Let's investigate it - depict sports in which "obese" athlets won gold medals, and for every sport depict the number of such athlets

In [ ]:
data[(data['Category_BMI'] == 'Obese') & (data['Medal'] == 'Gold')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,BMI,Category_BMI
524,297,Lala Abdul Rashid,M,38.0,169.0,91.0,Pakistan,PAK,1960 Summer,1960,Summer,Roma,Hockey,Hockey Men's Hockey,Gold,31.861629,Obese
620,359,Andrey Khakimovich Abduvaliyev,M,26.0,190.0,125.0,Unified Team,EUN,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Men's Hammer Throw,Gold,34.626039,Obese
1366,772,"Michael B. ""Mike"" Adam",M,24.0,175.0,95.0,Canada,CAN,2006 Winter,2006,Winter,Torino,Curling,Curling Men's Curling,Gold,31.020408,Obese
1527,846,Valerie Kasanita Adams-Vili (-Price),F,23.0,193.0,120.0,New Zealand,NZL,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Shot Put,Gold,32.215630,Obese
1528,846,Valerie Kasanita Adams-Vili (-Price),F,27.0,193.0,120.0,New Zealand,NZL,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Shot Put,Gold,32.215630,Obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268660,134407,Leonid Ivanovych Zhabotynskiy,M,30.0,189.0,163.0,Soviet Union,URS,1968 Summer,1968,Summer,Mexico City,Weightlifting,Weightlifting Men's Heavyweight,Gold,45.631421,Obese
269393,134800,Zhou Lulu,F,24.0,175.0,133.0,China,CHN,2012 Summer,2012,Summer,London,Weightlifting,Weightlifting Women's Super-Heavyweight,Gold,43.428571,Obese
269541,134872,Zhuang Xiaoyan,F,23.0,173.0,98.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Judo,Judo Women's Heavyweight,Gold,32.744161,Obese
269667,134947,Adrian Edward Zieliski,M,23.0,170.0,94.0,Poland,POL,2012 Summer,2012,Summer,London,Weightlifting,Weightlifting Men's Light-Heavyweight,Gold,32.525952,Obese
270034,135095,Szymon Zikowski,M,24.0,192.0,120.0,Poland,POL,2000 Summer,2000,Summer,Sydney,Athletics,Athletics Men's Hammer Throw,Gold,32.552083,Obese

In [ ]:
#your code here
data[(data['Category_BMI'] == 'Obese') & (data['Medal'] == 'Gold')].groupby('Sport')['Name'].nunique().sort_values(ascending=False)

Sport
Athletics        49
Weightlifting    45
Wrestling        25
Judo             19
Sailing           7
Baseball          7
Bobsleigh         5
Shooting          5
Archery           3
Hockey            3
Water Polo        3
Rowing            2
Curling           2
Ice Hockey        2
Softball          2
Boxing            1
Luge              1
Rugby Sevens      1
Name: Name, dtype: int64